[project]
name = "weather-comparison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=2.10.4",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.10",
]
